import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/assistant.mjs';
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.code=code;return this;},json(body){this.body=body;return this;}};}
test('assistant stays optional before keys are configured',async()=>{delete process.env.GROQ_API_KEY;delete process.env.WALLET_ASSISTANT_TOKEN;const res=response();await handler({method:'POST',headers:{}},res);assert.equal(res.code,503);assert.match(res.body.error,/setup is pending/);});
test('configured endpoint requires private passphrase',async()=>{process.env.GROQ_API_KEY='test-key';process.env.WALLET_ASSISTANT_TOKEN='test-passphrase';const res=response();await handler({method:'POST',headers:{},body:{message:'hello',accounts:[]}},res);assert.equal(res.code,401);assert.ok(!JSON.stringify(res.body).includes('test-key'));});
test('rejects malformed requests before reaching Groq',async()=>{const res=response();await handler({method:'POST',headers:{authorization:'Bearer test-passphrase'},body:{message:'x'.repeat(2001),accounts:[]}},res);assert.equal(res.code,400);});
test('rejects cross-origin requests',async()=>{const res=response();await handler({method:'POST',headers:{authorization:'Bearer test-passphrase',origin:'https://evil.example',host:'wallet.example'},body:{}},res);assert.equal(res.code,403);});
test('returns a proposed action without executing or exposing credentials',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({action:'show_summary',message:'Here is your summary.'})}}]})});try{const res=response();await handler({method:'POST',headers:{authorization:'Bearer test-passphrase'},body:{message:'Show balances',accounts:[]}},res);assert.equal(res.code,200);assert.equal(res.body.plan.action,'show_summary');assert.ok(!JSON.stringify(res.body).includes('test-key'));}finally{globalThis.fetch=original;}});
